[package]
name = "trojan-rust"
version = "0.4.0"
authors = ["cty123"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
byteorder = "1.4.3"
bytes = "1.1.0"
clap = "2.33.3"
env_logger = "0.9.0"
futures = { version = "0.3.18", features = ["thread-pool"]}
itertools = "0.10.1"
log = "0.4.14"
rustls = { version = "0.20.2", features = ["dangerous_configuration"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
sha2 = { version = "0.9.8" }
tokio = { version = "1.14.0", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["full"] }
tokio-stream = { version = "0.1.8" }
tokio-rustls = "0.23.1"
uninit = "0.4.0"
webpki-roots = "0.22.1"
rustls-pemfile = "0.2.1"
mockall = "0.10.2"

[lib]
name = "trojan_rust"
path = "src/lib.rs"

[[bin]]
name = "trojan-rust"
path = "src/main.rs"
