name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-macos-m4:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
        override: true
    - name: Install clang
      run: sudo apt-get update && sudo apt-get install -y clang
    - name: Create .cargo/config.toml
      run: |
        mkdir -p .cargo
        echo '[target.aarch64-apple-darwin]' >> .cargo/config.toml
        echo 'linker = "clang"' >> .cargo/config.toml
    - name: Build for aarch64-apple-darwin
      run: cargo build --target aarch64-apple-darwin --verbose
