name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/trojan-rust
            asset_name: trojan-rust-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/trojan-rust.exe
            asset_name: trojan-rust-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/trojan-rust
            asset_name: trojan-rust-macos

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    
    - name: Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
    
    - name: Release
      uses: softprops/action-gh-release@v0.1.7
      with:
        files: ${{ matrix.artifact_name }}
